:imagesdir: ../assets/images
include::style.adoc[]

== Apache Camel Workshop

Welcome to the Apache Camel workshop. Select a module below to get started.

{empty} +

[.tile]
****
xref:intro/intro.0.adoc[Introduction]

Get familiar with the workshop goals, the technologies at play, the scenario, and set up your development environment.

[.meta]
5 min | 4 tasks
****

[.tile]
****
xref:m1/m1.0.adoc[Lab 1 -- Scenario and Onboarding]

Introduces the first integration flow and helps you onboard onto the Matrix and Rocket.Chat chat platforms.

[.meta]
10 min | 4 tasks
****

[.tile]
****
xref:m2/m2.0.adoc[Lab 2 -- Kafka as the Backbone]

Decouple the messaging architecture using Streams for Apache Kafka, define common data models, and deploy the full solution on OpenShift.

[.meta]
19 min | 4 tasks
****

[.tile]
****
xref:m3/m3.0.adoc[Lab 3 -- Ingest Service]

TODO: Add description.

[.meta]
TODO
****

[.tile]
****
xref:m4/m4.0.adoc[Lab 4 -- AI assisted Customer support]

TODO: Add description.

[.meta]
TODO
****

[.tile]
****
xref:m5/m5.0.adoc[Lab 5 -- Protect LLM consumption with Connectivity Link]

TODO: Add description.

[.meta]
TODO
****
